"""adding archive

Revision ID: 356ba56ab0b6
Revises: 82b3c2a94283
Create Date: 2023-01-15 14:19:02.754932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356ba56ab0b6'
down_revision = '82b3c2a94283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_int', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('archived_int')

    # ### end Alembic commands ###
