"""followers

Revision ID: 799fb35a5cb3
Revises: 1ea0a80dd859
Create Date: 2023-01-11 16:34:23.672536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799fb35a5cb3'
down_revision = '1ea0a80dd859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_followers_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_followers_follower_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
