"""fixing

Revision ID: 982aa0de5410
Revises: 7ded8b032f52
Create Date: 2022-12-30 12:57:16.479465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982aa0de5410'
down_revision = '7ded8b032f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
